module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          tests: ['./tests/'],
          '@assets': ['./src/assets'],
          '@assets/': ['./src/assets/'],
          '@components': ['./src/components'],
          '@components/': ['./src/components/'],
          '@configs': ['./src/configs'],
          '@configs/': ['./src/configs/'],
          '@containers': ['./src/containers'],
          '@containers/': ['./src/containers/'],
          '@database': ['./src/database'],
          '@database/': ['./src/database/'],
          '@hocs': ['./src/hocs'],
          '@hocs/': ['./src/hocs/'],
          '@hooks': ['./src/hooks'],
          '@hooks/': ['./src/hooks/'],
          '@i18n': ['./src/i18n'],
          '@i18n/': ['./src/i18n/'],
          '@navigator': ['./src/navigator'],
          '@navigator/': ['./src/navigator/'],
          '@services': ['./src/services'],
          '@services/': ['./src/services/'],
          '@uikit': ['./src/components/uikit'],
          '@uikit/': ['./src/components/uikit/'],
          '@utils': ['./src/utils'],
          '@utils/': ['./src/utils/'],
          '@values': ['./src/values'],
          '@values/': ['./src/values/'],
          '@store': ['./src/store'],
          '@store/': ['./src/store/'],
        },
      },
    ],
  ],
};
